/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}'],
  darkmode: "class",
  theme: {
    fontFamily: {
      display: ['Lato', 'sans-serif'],
      body: ['Roboto', 'sans-serif']
    },
  },
  plugins: [require("@tailwindcss/typography"), require('daisyui')],
  daisyui: {
    themes: [
      {
        light: {
          ...require("daisyui/src/theming/themes")["[data-theme=light]"],
          "primary": "#A4784C",
          "primary-content": "#FFD587",
          "base-100": "#FBE7CC",
          "base-content": "#311706",
          "accent": "#DD6A6D",
          "neutral": "#0C0601",
          "neutral-focus": "#A5A29B",
          "neutral-content": "#CDC3BA",
          "info": "#0C0601",
          "info-content": "#CBD1DB",
          "warning": "#FEAD1A",
          "error": "#BA2829",
          "success": "#223A3A",
          "success-content": "#FBE7CC",
        },
        dark: {
          ...require("daisyui/src/theming/themes")["[data-theme=light]"],
          "primary": "#A4784C",
          "primary-content": "#FFD587",
          "base-content": "#FBE7CC",
          "base-100": "#311706",
          "accent": "#DD6A6D",
          "neutral": "#CDC3BA",
          "neutral-content": "#0C0601",
          "neutral-focus": "#A5A29B",
          "info": "#CBD1DB",
          "info-content": "#0C0601",
          "warning": "#FEAD1A",
          "error": "#BA2829",
          "success": "#223A3A",
          "success-content": "#FBE7CC",
        },
      },
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
    ]
  },
}
